[[stack]]
name = "media"
description = "Plex Media Server and Transmission torrent client."
tags = ["media-services", "home"]
deploy = true

[stack.config]
server = "home"
files_on_host = false
git_provider = "github.com"
git_https = true
repo = "jrudavicius/home-server"
branch = "main"
run_directory = "stacks/media"
file_paths = ["docker-compose.yml"]
project_name = "media"
auto_pull = true
webhook_enabled = true
webhook_force_deploy = true
environment = """
PLEX_PORT=32400
PLEX_CLAIM=[[PLEX_CLAIM]]
PLEX_CONFIG_PATH=[[PLEX_CONFIG_PATH]]
TRANSCODE_PATH=[[TRANSCODE_PATH]]
MEDIA_PATH=[[MEDIA_PATH]]

TRANSMISSION_WEB_PORT=9091
TRANSMISSION_PEER_PORT=51413
TRANSMISSION_USERNAME=julius
TRANSMISSION_CONFIG_PATH=[[TRANSMISSION_CONFIG_PATH]]
TRANSMISSION_USER_PASSWORD_FILE=[[TRANSMISSION_USER_PASSWORD_FILE]]
"""
